disabled_rules:
  - weak_delegate
  - opening_brace
opt_in_rules:
  - array_init
  - capture_variable
  - collection_alignment

line_length:
  warning: 220
  error: 240

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 80
    error: 100
  excluded:
    - id
  allowed_symbols:
    - '_'

trailing_comma:
  mandatory_comma: true