disabled_rules:
  - weak_delegate
opt_in_rules:
  - array_init
  - capture_variable
  - collection_alignment

line_length:
  warning: 180
  error: 200

identifier_name:
  min_length:
    warning: 3
    error: 2
  excluded:
    - id
  allowed_symbols:
    - '_'

trailing_comma:
  mandatory_comma: true