disabled_rules:
  - trailing_comma
opt_in_rules:
  - array_init
  - capture_variable
  - collection_alignment

line_length:
  warning: 220
  error: 240

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 80
    error: 100
  allowed_symbols:
    - '_'

type_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 80
    error: 100
  excluded:
    - ''

nesting:
  type_level: 2
  function_level: 3
