on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      release-upload-url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
  release:
    name: Release
    needs: create-release
    strategy:
      matrix:
        target-platform: [iOS, macOS]
      fail-fast: false
    runs-on: macOS-latest
    env:
      APPLE_ID: "bot@sinoru.io"
      IPA_PATH: "TweetNest (${{ matrix.target-platform }}).ipa"
      KEYCHAIN_NAME: "build.keychain"
      MATCH_READONLY: 1
      PKG_PATH: "TweetNest (${{ matrix.target-platform }}).pkg"
      SPACESHIP_SKIP_2FA_UPGRADE: 1
      XCARCHIVE_NAME: TweetNest (${{ matrix.target-platform }}).xcarchive
      XCARCHIVE_PATH: "archive/TweetNest (${{ matrix.target-platform }}).xcarchive"
    steps:
      - uses: actions/checkout@v2
      - name: Add Deploy Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Setup Keychain
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
          security default-keychain -s "$KEYCHAIN_NAME"
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.APPLE_CERTIFICATES_PASSWORD }}
      - uses: sinoru/actions-setup-xcode@v1.1
        with:
          xcode-version: 12.4
          apple-id: bot@sinoru.io
          apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Archive
        run: |
          case "${{ matrix.target-platform }}" in
            "iOS") bundle exec fastlane ios archive;;
            "macOS") bundle exec fastlane mac archive;;
            *) exit 1;;
          esac
        env:
          GYM_ARCHIVE_PATH: ${{ env.XCARCHIVE_PATH }}
          MATCH_KEYCHAIN_NAME: ${{ env.KEYCHAIN_NAME }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.APPLE_CERTIFICATES_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.APPLE_CERTIFICATES_PASSWORD }}
      - run: hdiutil create -format ULFO -srcfolder archive "$XCARCHIVE_NAME.dmg"
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.release-upload-url }}
          asset_path: ./${{ env.XCARCHIVE_NAME }}.dmg
          asset_name: ${{ env.XCARCHIVE_NAME }}.dmg
          asset_content_type: application/x-apple-diskimage
      - name: Release (iOS)
        if: ${{ matrix.target-platform == 'iOS' }}
        run: bundle exec fastlane ios release
        env:
          FASTLANE_USER: ${{ env.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          GYM_ARCHIVE_PATH: ${{ env.XCARCHIVE_PATH }}
          GYM_OUTPUT_NAME: ${{ env.IPA_PATH }}
          MATCH_KEYCHAIN_NAME: ${{ env.KEYCHAIN_NAME }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.APPLE_CERTIFICATES_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.APPLE_CERTIFICATES_PASSWORD }}
      - name: Release (macOS)
        if: ${{ matrix.target-platform == 'macOS' }}
        run: bundle exec fastlane mac release
        env:
          FASTLANE_USER: ${{ env.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          GYM_ARCHIVE_PATH: ${{ env.XCARCHIVE_PATH }}
          GYM_OUTPUT_NAME: ${{ env.PKG_PATH }}
          MATCH_KEYCHAIN_NAME: ${{ env.KEYCHAIN_NAME }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.APPLE_CERTIFICATES_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.APPLE_CERTIFICATES_PASSWORD }}
      - name: Upload IPA to Release
        if: ${{ matrix.target-platform == 'iOS' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.release-upload-url }}
          asset_path: ./${{ env.IPA_PATH }}
          asset_name: ${{ env.IPA_PATH }}
          asset_content_type: application/zip
      - name: Upload PKG to Release
        if: ${{ matrix.target-platform == 'macOS' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.release-upload-url }}
          asset_path: ./${{ env.PKG_PATH }}
          asset_name: ${{ env.PKG_PATH }}
          asset_content_type: application/octet-stream
