name: SwiftLint

on:
  push:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: git clone https://github.com/realm/SwiftLint.git -b 0.44.0 ~/.swiftlint
      - uses: sinoru/actions-setup-swift@v2
        with:
          swift-version: '5.4.3'
      - run: swift build --package-path ~/.swiftlint -c release
      - run: swiftenv install 5.5-DEVELOPMENT-SNAPSHOT-2021-09-06-a
      - run: |
          swift run --package-path ~/.swiftlint -c release --skip-build -- swiftlint | sed -E "s/$(pwd|sed 's/\//\\\//g')\///" | sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 file=\1,line=\2,col=\3::\5/'
          # MIT License
          # 
          # Copyright (c) 2018 Norio Nomura

          # Permission is hereby granted, free of charge, to any person obtaining a copy
          # of this software and associated documentation files (the "Software"), to deal
          # in the Software without restriction, including without limitation the rights
          # to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
          # copies of the Software, and to permit persons to whom the Software is
          # furnished to do so, subject to the following conditions:

          # The above copyright notice and this permission notice shall be included in all
          # copies or substantial portions of the Software.

          # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
          # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
          # FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
          # AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
          # LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
          # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
          # SOFTWARE.
          #
          # https://github.com/norio-nomura/action-swiftlint/blob/9f4dcd7fd46b4e75d7935cf2f4df406d5cae3684/entrypoint.sh
        env:
          SWIFT_VERSION: 5.5-DEVELOPMENT-SNAPSHOT-2021-09-06-a
