name: Test

on:
  push:
    paths-ignore:
    - CHANGELOG.md
    - LICENSE
    - README.md

env:
  APPLE_ID: "bot@sinoru.io"
      
jobs:
  test-TweetNestKit-iOS:
    name: Test TweetNestKit (iOS)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: sinoru/actions-setup-xcode@v2
      with:
        xcode-version: 12.4
        apple-id: ${{ env.APPLE_ID }}
        apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: bundle exec fastlane scan -s "TweetNest (iOS)"

  test-TweetNestKit-macOS:
    name: Test TweetNestKit (macOS)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: sinoru/actions-setup-xcode@v2
      with:
        xcode-version: 12.4
        apple-id: ${{ env.APPLE_ID }}
        apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: bundle exec fastlane scan -s "TweetNest (macOS)"

  test-TweetNest-iOS:
    name: Test TweetNest (iOS)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: sinoru/actions-setup-xcode@v2
      with:
        xcode-version: 12.4
        apple-id: ${{ env.APPLE_ID }}
        apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: bundle exec fastlane scan -s "TweetNest (iOS)"

  test-TweetNest-macOS:
    name: Test TweetNest (macOS)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: sinoru/actions-setup-xcode@v2
      with:
        xcode-version: 12.4
        apple-id: ${{ env.APPLE_ID }}
        apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: bundle exec fastlane scan -s "TweetNest (macOS)"
